classdef DirLotTestSuite < TestSuite
    %DIRLOTTESTSUITE Test suite for dirlot
    %
    % SVN identifier:
    % $Id: DirLotTestSuite.m 249 2011-11-27 01:55:42Z sho $
    %
    % Requirements: MATLAB R2008a, mlunit_2008a
    %
    % Copyright (c) 2011, Shogo MURAMATSU
    %
    % All rights reserved.
    %
    % Contact address: Shogo MURAMATSU,
    %                Faculty of Engineering, Niigata University,
    %                8050 2-no-cho Ikarashi, Nishi-ku,
    %                Niigata, 950-2181, JAPAN
    %
    properties
    end
    
    methods
        function ste = suite(this)
            ste = {
                'dirlot.SubbandSpecificationTestCase',...
                'dirlot.PolyPhaseMatrix2dTestCase',...
                'dirlot.GivensRotationsTestCase',...
                'dirlot.LpPuFb2dVm0TestCase',...
                'dirlot.LpPuFb2dVm1TestCase',...
                'dirlot.LpPuFb2dVm2TestCase',...
                'dirlot.LpPuFb2dTvmTestCase',...
                'dirlot.LpPuFb2dFactoryTestCase',...
                'dirlot.PassBandErrorStopBandEnergyTestCase',...
                'dirlot.AmplitudeErrorEnergyTestCase',...
                'dirlot.CodingGainTestCase',...
                'dirlot.LpPuFb2dDesignerFrTestCase',...
                'dirlot.LpPuFb2dDesignerCgTestCase',...
                'dirlot.ForwardDirLotTestCase',...
                'dirlot.InverseDirLotTestCase',...
                'dirlot.EcsQuantizerDeQuantizerTestCase',...
                'dirlot.UniformSubbandQuantizerTestCase',...
                'dirlot.DirectionalDwtQuantizerTestCase'
                };
        end
    end
end
